KZ-314 Migrate button component
clippings/paper pull request #12
Opened 2020-10-22 15:06 UTC by T3ch0o

## What is this about?

Migrating the existing Buttons.js file from clippings project

## Checklist

- [x] Add buttons
- [x] Add buttons stories
- [x] Add buttons scss

2020-10-22 15:19 UTC, EZarkov requested changes
Remove usage of Icomoon and use internal svg icons

2020-10-26 12:08 UTC, MartinAndreev approved these changes

2020-10-26 14:56 UTC, EZarkov requested changes

2020-10-26 14:56 UTC, EZarkov commented on src/assets/scss/button.scss
> +    color: #ffffff;
This should be a variable.

2020-10-26 14:56 UTC, EZarkov commented on src/assets/scss/button.scss
> +      fill: #ffffff;
This should be a variabale.

2020-10-26 14:56 UTC, EZarkov commented on src/core/utils/ClassNameModifierUtil.ts
> +const buttonPrefix = 'uni-button'; // TODO: replace with "button" after buttons-refactoring is complete
This should be renamed to `p-button`

2020-10-26 16:17 UTC, EZarkov reviewed
@T3ch0o Do we need button prefix variables at all?

2020-10-26 16:52 UTC, T3ch0o commented
@EZarkov Well since all components have some kind of a prefix and especially this one needs variables, according to me we need to keep it that way.

2020-10-26 17:01 UTC, EZarkov approved these changes

2020-10-26 18:09 UTC, merged