DEM-1875 overlay component
clippings/paper pull request #14
Opened 2020-10-23 12:43 UTC by AngelGenchev95

Dem-1875

2020-10-23 12:53 UTC, RusiPapazov commented on src/assets/scss/components.scss
> +  position:relative;
```suggestion
  position: relative;
```

2020-10-26 06:58 UTC, T3ch0o approved these changes

2020-10-26 13:57 UTC, RusiPapazov commented on src/stories/Overlay/Overlay.stories.tsx
> +  <Overlay content={<Text>Overlay text</Text>} open={true}>
```suggestion
  <Overlay content={<Text>Overlay text</Text>}>
```

2020-10-26 13:57 UTC, RusiPapazov commented on src/components/Overlay/enums/OverlayPositioningEnum.ts
> +  CENTERED = 'centered',
Want to add this here as well - do we need a positioning enum if it's only one and will possibly never change to two options?

2020-10-26 14:01 UTC, AngelGenchev95 commented on src/components/Overlay/enums/OverlayPositioningEnum.ts
> +  CENTERED = 'centered',
I feel that we might have some more positioning in the future so it makes sense to have it preplanned. I guess @T3ch0o  and @EZarkov can also chime in here

2020-10-26 14:02 UTC, RusiPapazov commented on src/components/Overlay/enums/OverlayPositioningEnum.ts
> +  CENTERED = 'centered',
You what they say - YAGNI 😄 . But I'm ok with it either way.

2020-10-26 14:37 UTC, EZarkov requested changes

2020-10-26 14:37 UTC, EZarkov commented on src/components/Overlay/enums/OverlayPositioningEnum.ts
> +  CENTERED = 'centered',
@AngelGenchev95 Here @RusiPapazov Is 100% right We will implement the positioning we needed. KISS & YAGNI. There is a better way to achieve it. The content will be div with 100% width and 100% height and inside it, the inner content can be placed how it is needed. Please remove this option for now.

2020-10-28 15:09 UTC, EZarkov approved these changes

2020-10-28 15:15 UTC, merged