CAT-1946: Drawer component
clippings/paper pull request #24
Opened 2020-12-07 21:56 UTC by MartinAndreev

**What is this about?**
https://clippings.atlassian.net/browse/CAT-1946

**Checklist**

- [x] Done
- [x] Fix storybook docs
- [x] Request 1st reviewer early
- [x] Request 2nd reviewer

2020-12-08 16:55 UTC, AngelGenchev95 approved these changes

2020-12-09 10:47 UTC, maria-clipp commented on src/components/Drawer/Drawer.tsx
> +  console.log(isNaN(Number(width)));
Could you please remove the console log :D

2020-12-09 10:50 UTC, maria-clipp approved these changes

2020-12-09 13:17 UTC, MartinAndreev commented on src/components/Drawer/Drawer.tsx
> +  console.log(isNaN(Number(width)));
👍  Thx had forgotten it 😆

2020-12-09 13:31 UTC, EZarkov requested changes
At the moment this component doesn't support to be closed if you click out side.

2020-12-09 13:31 UTC, EZarkov commented on src/components/Drawer/styles/DrawerStyles.tsx
> +  width: ${props => (isNaN(Number(props.width)) ? props.width : `${props.width}px`)};
It will be better not to support both number and string. WEshoud restrict user to use valid `width` property '200px', '10rem' https://developer.mozilla.org/en-US/docs/Web/CSS/width

2020-12-09 13:32 UTC, MartinAndreev commented on src/components/Drawer/styles/DrawerStyles.tsx
> +  width: ${props => (isNaN(Number(props.width)) ? props.width : `${props.width}px`)};
We had a chat with @maria-clipp and @AngelGenchev95 exactly for that and if we do that we wont be able to make the drawer 100% or 50vh.

2020-12-09 13:34 UTC, MartinAndreev commented on src/components/Drawer/styles/DrawerStyles.tsx
> +  width: ${props => (isNaN(Number(props.width)) ? props.width : `${props.width}px`)};
@EZarkov We can add a separate property for the unit and allow px, rem, %, vh, vw?

2020-12-09 13:37 UTC, EZarkov commented on src/components/Drawer/styles/DrawerStyles.tsx
> +  width: ${props => (isNaN(Number(props.width)) ? props.width : `${props.width}px`)};
```js
<Drawer width={100} /> //-> 100px #drop this support enforce <Drawer width='100px' />
<Drawer width={'100%'} /> //-> 100%
```

2020-12-09 13:39 UTC, MartinAndreev commented on src/components/Drawer/styles/DrawerStyles.tsx
> +  width: ${props => (isNaN(Number(props.width)) ? props.width : `${props.width}px`)};
👍

2020-12-09 16:48 UTC, EZarkov approved these changes

2020-12-10 14:37 UTC, merged