Added ref to the badge component
clippings/paper pull request #28
Opened 2020-12-21 12:15 UTC by maria-clipp

The react-bootstrap OverlayTrigger component,  that we use for the tooltips, requires the triggering components to accept a ref.

2020-12-21 15:38 UTC, RusiPapazov requested changes

2020-12-21 15:38 UTC, RusiPapazov commented on src/components/Badge/Badge.tsx
> +      <span>Badge</span>
```suggestion
```

2020-12-21 16:13 UTC, MartinAndreev approved these changes

2020-12-22 08:36 UTC, RusiPapazov approved these changes

2020-12-22 08:37 UTC, RusiPapazov commented
You can link the PR to the Jira issue DEM-1953 by just adding it in the name.

2020-12-22 09:31 UTC, merged