Kz 204 migrate components
clippings/paper pull request #3
Opened 2020-09-28 15:54 UTC by T3ch0o

**What is this about?**

**Checklist**

- [x] Migrate all existing components from the current Paper folder inside clippings repo
- [x] Refactor them to use typescript
- [x] Add storybook
- [x] Update dependencies
- [x] Change eslint rules
- [x] Better project architecture

2020-09-28 15:58 UTC, T3ch0o commented
"@typescript-eslint/no-empty-function" is turned off because sometimes we use a function as a bootstrap to execute multiple functionalities
"react/display-name" is turned off because in our storybook requires to specify our component name which is unreasonable for me to do this on every single component since in the UI we clearly see what we are looking at.

2020-10-01 09:47 UTC, MartinAndreev requested changes
Most of it looks ok, but I have a few notes.

I think we should always specify the default props and thus remove the need for optional types. If someone needs the explicitly make a prop type optional, we can always use Parial<PropType>

For functions its better to use the () => void or (params) => returnType syntax. I think there is even a eslint rule for it.

For PropTypes, the usage of Type is better vs the Interfaces. I have added notes why in one of the comments.

2020-10-01 09:47 UTC, MartinAndreev commented on package.json
> +  "author": "Stoyan Kalpakchiev <t3cho.k@gmail.com>, Evstati Zarkov <evstati.zarkov@gmail.com>",
Can you change this to Clippings Devs <devs@clippings.com>?

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Accordion/contexts/AccordionContext.ts
> +  onClick: (id?: number | string): any => () => {},
```suggestion
  onClick: (id?: number | string): void => () => {},
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Accordion/contexts/AccordionItemContext.ts
> +  handleOpen: (): any => null,
```suggestion
  handleOpen: (): void => null,
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Accordion/intefaces/AccordionInterface.ts
> +  disabled?: boolean;
You can make them required and pass default values.

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Accordion/intefaces/AccordionInterface.ts
> +  disabled?: boolean;
I think this should be applied to all the components, otherwise we have to always check for undefined.

Also, PropTypes should be better defined as Types. Interfaces are better used for public API-s.
It is mostly because interfaces can be declared multiple times.

```typescript
interface User {
    name: string;
}

interface User {
    lastname: string;
}

const user: User = {name: "Foo", lastname: "Bar"}; // No compilation error

type User {
    name: string;
}

type User {
    lastname: string;
}
// Compilation error "Duplicate identifier 'User'."
```

Here is a good article: https://dev.to/reyronald/typescript-types-or-interfaces-for-react-component-props-1408

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Accordion/intefaces/AccordionItemInterface.ts
> +  onOpen?: Function;
Better use

```suggestion
  onOpen?: () => void;
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Accordion/intefaces/AccordionItemInterface.ts
> +  eventKey?: number | any | string;
If you use any, the number and string are not needed.

```suggestion
  eventKey: any;
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteHit.tsx
> +  const ref: React.MutableRefObject<any> = useRef();
```suggestion
  const ref = useRef<HTMLDivElement>();
```

If you specify it like this, it will use the type returned by useRef.

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteInput.tsx
> +  const ref: React.MutableRefObject<any> = useRef();
You can do the same here.

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteInput.tsx
> +  const onSearchLimited = (searched: string) => {
```suggestion
  const onSearchLimited = (searched: string): void => {
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteInput.tsx
> +  const onClick = (itemValue: { label: string }) => {
```suggestion
  const onClick = (itemValue: { label: string }): void => {
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteInput.tsx
> +  const onInputChange = event => {
```suggestion
  const onInputChange = (event): void => {
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteInput.tsx
> +  const findElementIndex = (hits, search) => hits.findIndex(hit => hit.label === search);
```suggestion
  const findElementIndex = (hits, search): number  => hits.findIndex(hit => hit.label === search);
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/AutocompleteInput.tsx
> +  const onInputKeyUp = event => {
```suggestion
  const onInputKeyUp = (event):void => {
```

2020-10-01 09:47 UTC, MartinAndreev commented on src/components/Autocomplete/interfaces/AutocompleteHitInterface.ts
> +  scrollTo: Function;
```suggestion
  scrollTo: () => void;
```

You should use this instead of the Function type.

2020-10-01 09:48 UTC, MartinAndreev commented
Also we shoud add the jest tests as part of the build.

2020-10-01 11:31 UTC, T3ch0o commented on src/components/Accordion/intefaces/AccordionInterface.ts
> +  disabled?: boolean;
Okay than i will switch to types instead

2020-10-01 13:48 UTC, EZarkov commented
> Also we should add the jest tests as part of the build.

@MartinAndreev could you elaborate because on push we are executing tests, linting and Typescript check 

 https://github.com/clippings/paper/pull/3/checks?check_run_id=1193244331

2020-10-01 13:49 UTC, MartinAndreev commented
@EZarkov Sorry, missed that one. I was used to travis 👍

2020-10-01 14:37 UTC, MartinAndreev approved these changes
Looks good, there are some small issues, but they can be fixed later, if you cannot do it now.

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/Accordion/contexts/AccordionContext.ts
> +  onClick: (id?: number | string | null): any => () => {},
```suggestion
  onClick: (id?: number | string | null): void => () => {},
```

Normally the callbacks do not return a value, so you can just add them as void.

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/DateInput/DateInput.tsx
> +export const DateInput: React.FunctionComponent<DateInputPropsTypes> = ({
Just as a side note, you can use FC for short.

```typescript
import React, { FC } from 'react';
```

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/Icon/Icon.tsx
> +  const buildIconProps: any = ({
You can remove the :any, it should inherit the type from the function definition.

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/Icon/constants/IconsMap.ts
> +const iconsMap = {
Not sure if we will need the type definition, but if its needed you can add it as

```typescript
const iconsMap: {[key: ICON]: string}

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/Icon/enums/IconsColorEnum.ts
> +//  WHITE: '#ffffff',
Do we need these?

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/Icon/types/IconPropsType.ts
> +  direction?: any;
```suggestion
  color?: ICONS_COLOR;
  size?: ICONS_SIZE;
  direction?: any;
```

Also do we have a enum for the direction?

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/ImageCover/types/ImageCoverPropsType.ts
> +import React from 'react';
I am not sure if we should extract prop types in a separate file, as the types themself are not part of the public API.
@EZarkov any thoughts?

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/SearchInput/types/SearchInputPropsType.ts
> +  submitOn?: any;
```suggestion
  submitOn?: SUBMIT_TYPE;
```

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/SearchInput/types/SearchInputPropsType.ts
> +  onChange: (...args: any) => any;
```suggestion
  onChange: (value: string) => any;
```

2020-10-01 14:37 UTC, MartinAndreev commented on src/components/TextInput/types/TextInputPropsType.ts
> +  onChange: Function;
```suggestion
  onChange: (value: string) => void;
```

2020-10-01 14:39 UTC, MartinAndreev commented
Just on a side note for future reference, don't use :any if you know the type. Most of the callbacks return a strict type or a set of types like number | string | object

2020-10-02 07:43 UTC, EZarkov requested changes
LGTM. Only a quick suggestion. Could you add an alias for `../../core/`, types, enums and replace relative imports?

2020-10-02 11:24 UTC, EZarkov approved these changes

2020-10-02 15:16 UTC, merged