Selector UI
clippings/paper pull request #31
Opened 2021-01-21 16:38 UTC by EZarkov

Add new selector UI

- [x] Add Selector componets
- [ ] Add Item components

2021-01-21 16:52 UTC, MartinAndreev requested changes

2021-01-21 16:52 UTC, MartinAndreev commented on src/components/Selector/SelectorItem.tsx
> +      <Avatar src={avatar} shape={avatarShape} />
I think avatar should be react node. Otherwise we are limiting it to only paper components. What if I wanted to add a custom avatar? Same goes with the text inside the text container. Don't do text/ subtext additional. Just to {children}.

2021-01-21 16:52 UTC, MartinAndreev commented on src/components/Selector/SelectorItem.tsx
> +      <Avatar src={avatar} shape={avatarShape} />
Good example is https://material-ui.com/components/menus/ where you can use both MenuItem and MenuList as child components. I think we can separate them so it depends on the component pass to the child like ActionSelectorItem and SelectorItem

2021-01-21 16:57 UTC, EZarkov commented on src/components/Selector/SelectorItem.tsx
> +      <Avatar src={avatar} shape={avatarShape} />
The idea of `<SelectorItem>` is to be a high order component that will render like this. What you referring is `<SelectorRow>` And you can build it as you want. At this point you have option to build your custom  item with `<SelectorRow>` or to use predefined `<SelectorItem>`.

2021-01-21 17:40 UTC, MartinAndreev commented on src/components/Selector/SelectorItem.tsx
> +      <Avatar src={avatar} shape={avatarShape} />
Yes buy why need the high order component, when we can split it into more simpler reusable components. For example instead if the additional text you may have and icon, one line text instead of two and a image and voila, you have the project selector

2021-01-21 17:45 UTC, MartinAndreev commented on src/components/Selector/SelectorItem.tsx
> +      <Avatar src={avatar} shape={avatarShape} />
If you want to create a high order component make a VariantSelectorItem one, which underneath uses avatar, the child inside the textarea and an Action component as additional build inside the Selector item and return it. Otherwise the component has a specific case, which fits our need only

2021-01-22 15:42 UTC, EZarkov commented
@MartinAndreev @maria-clipp Selector components have been updated as we discused. Thank you for you suggestions.

2021-01-22 16:10 UTC, MartinAndreev reviewed
I am happy with the implementaion.

2021-01-25 10:18 UTC, maria-clipp requested changes

2021-01-25 10:18 UTC, maria-clipp commented on src/components/Card/styles/Card.ts
> +import styled from 'styled-components';
NOTE/IDEA: I am not sure about the exact use case of this component, but it can be implemented using hidden radio buttons and it will give us the selected status for styling out and will deselect the previous element of the box. This is assuming that we can select only one option

2021-01-25 10:21 UTC, maria-clipp commented
The lists that we are using will probably have a lot of values so we can add a lazyloading/infinityscroll container as an improvement at some point.

2021-01-25 10:53 UTC, EZarkov commented on src/stories/Text/Text.stories.tsx
> +    <Text type={TEXT_TYPE.SMALL}>A small text</Text>
Based on the defined type we have to use `TEXT_TYPE` https://github.com/clippings/paper/blob/master/src/components/Text/types/TextPropsType.ts#L6

2021-01-25 10:54 UTC, EZarkov commented on src/components/Card/styles/Card.ts
> +import styled from 'styled-components';
It can but as HOC because in this case, we have only one selected for ather case we can have multiple selections.

2021-01-25 11:09 UTC, MartinAndreev approved these changes

2021-01-25 11:10 UTC, maria-clipp commented on src/components/Card/styles/Card.ts
> +import styled from 'styled-components';
Yes, we can have types ``` singleSelect ``` and ``` multySelect ``` that can use checkboxes and radio buttons and change the input type that we are using. Still, it is just an idea.

2021-01-25 11:11 UTC, maria-clipp approved these changes

2021-01-25 11:11 UTC, MartinAndreev commented
@maria-clipp I was thinking of introducing virtualization in some point of the future.

2021-01-25 11:19 UTC, maria-clipp commented
@MartinAndreev maybe it is a good idea to keep a list of features that we know we will need, so we can implement them on innovation days or similar, so they can be ready in advance.

2021-01-25 11:25 UTC, MartinAndreev commented
@maria-clipp Created an issue for it :)

2021-01-25 13:10 UTC, merged