DD-209 Add different field types
clippings/paper pull request #49
Opened 2021-06-22 12:36 UTC by maria-clipp

**What is this about?**
DD-209 
We need to be able to change the type of an input
**Checklist**

- [x] Extract input component
- [x] Create a field component that will be a complex input with validation and labels
- [x] Update current text component to use Field component
- [ ] Create email component
- [] Request 1st reviewer early
- [] Request 2nd reviewer

2021-06-22 14:50 UTC, EZarkov commented on src/components/FIeld/Field.tsx
> +export const Field: React.ForwardRefExoticComponent<
There is typo in `src/components/FIeld/Field.tsx`,  `FIeld` directory should be `Field`

2021-06-25 10:29 UTC, AngelGenchev95 requested changes

2021-06-25 10:29 UTC, AngelGenchev95 commented on package.json
> +  "version": "1.2.29",
https://semver.org/ This should be changed to 1.2.0

2021-06-25 10:29 UTC, AngelGenchev95 commented on src/stories/SimpleInputTypes/SimpleInputTypes.stories.mdx
> +Please be advised when you use different types of field they will come with the validation of the specific type. To ignore that validation add `novalidate` attribute to the form
Just a suggestion. Instead of insisting on having `novalidate` in the form maybe we can add formnovalidate to submit buttons and keep the logic entirely in paper.

2021-06-25 12:32 UTC, maria-clipp commented on src/stories/SimpleInputTypes/SimpleInputTypes.stories.mdx
> +Please be advised when you use different types of field they will come with the validation of the specific type. To ignore that validation add `novalidate` attribute to the form
We do not have a separate submit button and we use our buttons not only informs. 

Usually, it will be better to for the paper user to decide if they want to use the native validation or not. Not user what is best in our case.

2021-06-25 12:33 UTC, AngelGenchev95 commented on src/stories/SimpleInputTypes/SimpleInputTypes.stories.mdx
> +Please be advised when you use different types of field they will come with the validation of the specific type. To ignore that validation add `novalidate` attribute to the form
We could check the button type and decide based on that. The second part is a fair point though

2021-06-28 09:02 UTC, AngelGenchev95 approved these changes

2021-06-28 10:18 UTC, EZarkov approved these changes

2021-06-28 10:28 UTC, merged