Donald/Migrate old button component
clippings/paper pull request #59
Opened 2022-02-02 10:04 UTC by Donaldzzq

2022-02-03 10:14 UTC, AngelGenchev95 requested changes

2022-02-03 10:14 UTC, AngelGenchev95 commented on src/components/Buttons/Button.tsx
> +export const Button = styled(CustomizeButton)<ButtonPropsType>(() => ({}));
Do you think that rather than doing it like this we can instead directly style the `<MaterialButton />` and export that, skipping the `<CustomizeButton/>` component ?

2022-02-03 10:17 UTC, AngelGenchev95 requested changes

2022-02-03 10:17 UTC, AngelGenchev95 commented on src/components/Buttons/Button.tsx
> +const CustomizeButton: React.FunctionComponent<ButtonPropsType> = ({
Instead of having a file like this can we directly export it in `Index.component.ts` ?

2022-02-03 14:22 UTC, Donaldzzq commented on src/components/Buttons/Button.tsx
> +const CustomizeButton: React.FunctionComponent<ButtonPropsType> = ({
Sure!

2022-02-10 15:55 UTC, AngelGenchev95 approved these changes

2022-02-14 10:26 UTC, merged