migrate overlay component
clippings/paper pull request #65
Opened 2022-02-14 09:55 UTC by Donaldzzq

2022-02-14 12:07 UTC, maria-clipp commented on src/components/Overlay/Overlay.tsx
> -      className={classnames(className, classNames.overlay.content, {
Remove all old styles

2022-02-14 13:09 UTC, AngelGenchev95 approved these changes

2022-02-16 08:47 UTC, maria-clipp requested changes

2022-02-16 08:47 UTC, maria-clipp commented on src/components/Overlay/Overlay.tsx
>    zIndex = 1050,
There is a console error  `index.js:136 Warning: React does not recognize the `zIndex` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `zindex` instead. If you accidentally passed it from a parent component, remove it from the DOM element.` please taka e look

2022-02-16 15:25 UTC, merged