Implement Navigator Widget
clippings/paper pull request #75
Opened 2022-02-24 12:59 UTC by Donaldzzq

2022-03-09 15:08 UTC, maria-clipp requested changes

2022-03-09 15:08 UTC, maria-clipp commented on src/components/NavBarActions/NavBarActions.tsx
> +          label: 'Saved Items',
The actual label and the link should be something that is passed to the component and matched to the icon by id for example

2022-03-09 15:08 UTC, maria-clipp commented on src/components/NavBarActions/styles/NavBarActionsStyles.ts
> +export const StyledIconContainer: React.FC = styled('div')(() => ({
Material has some container components that should have margins and padding set from the theme. Can we use some of them instead of creating containers on our own?

2022-03-09 15:08 UTC, maria-clipp commented on src/components/QuotePopover/QuoteItem/QuoteItem.tsx
> +    <Link href={`/quote/${quote.id}`} underline="none">
```suggestion
    <Link href={quote.url} underline="none">
```

2022-03-09 15:08 UTC, maria-clipp commented on src/components/QuotePopover/QuotePopover.tsx
> +      <Link href={`/quote/all`} underline="none">
the link is something that will be passed to the component

2022-03-09 15:09 UTC, maria-clipp commented on src/components/AccountPopover/AccountPopover.tsx
> +interface AccountPopoverProps {
Please use type instead of interface and put all types In a folder similar to the old components

2022-03-11 12:08 UTC, maria-clipp commented on src/components/AccountPopover/styles/AccountPopoverStyles.tsx
> +  '& a': {
The style nesting should be done by referring to the component itself. Please check the example https://styled-components.com/docs/advanced#referring-to-other-components.

2022-03-30 07:05 UTC, maria-clipp commented on src/components/CartPopover/CartPopover.tsx
> +        <div>Coming soon</div>
if the user is logged in the quote pop over should be displayed if there are any quotes

2022-03-30 07:08 UTC, maria-clipp commented on src/widget/NavBar/NavBar.tsx
> +        <LanguageSelector options={languageList} value={language} onChange={handleLanguageChange} />
There is a console error and a default value is needed

2022-03-30 07:12 UTC, maria-clipp commented on src/components/NavBarActions/NavBarActions.tsx
> +        <Badge color="error" badgeContent={notificationCount} onClick={handleCartClick}>
Please put the 2 actions in separate components one for cart and one for the account

2022-03-30 07:13 UTC, maria-clipp commented on src/components/NavBarActions/NavBarActions.tsx
> +        <Badge color="error" badgeContent={0} onClick={handleAccountClick}>
the account will not have notifications so the badge is not needed

2022-03-30 07:21 UTC, maria-clipp requested changes

2022-03-30 07:21 UTC, maria-clipp commented on src/components/QuotePopover/QuotePopover.tsx
> +      {quotesCount > 0 &&
you can use `:last-of-type` to add or remove the border for the quote item instead of adding a divider component

2022-03-30 07:21 UTC, maria-clipp commented on src/components/NavBarActions/NavBarActions.tsx
> +            <QuotePopover isSignin={isSignin} quotes={quotes} willAllQuoteLink={willAllQuoteLink} />
`willAllQuoteLink` does not feel like something that we need we should always have that button unless there are no quotes if we do not have any quotes please check https://www.figma.com/file/LHWaVfWI1c0YK9rSGMHrnc/Concepts-(MUI)?node-id=14%3A1609

2022-03-30 07:22 UTC, maria-clipp commented on src/components/QuotePopover/styles/QuotePopoverStyles.tsx
> +  '& button': {
we should have this from the theme,  please apply it and check

2022-03-31 08:27 UTC, maria-clipp approved these changes

2022-03-31 13:26 UTC, AngelGenchev95 approved these changes

2022-03-31 13:34 UTC, merged