Init PDP widget
clippings/paper pull request #77
Opened 2022-02-28 16:07 UTC by Donaldzzq

2022-03-09 15:19 UTC, maria-clipp requested changes

2022-03-09 15:19 UTC, maria-clipp commented on src/components/PDPOptionsSelector/PDPOptionsSelector.tsx
> +          <Select
This should not be a select, but something like read-only input that has an image since wen we click it it should open the swatch drawer or the bigger PDP modal/screen

2022-03-09 15:19 UTC, maria-clipp commented on src/components/QuantityInput/QuantityInput.tsx
> +          InputProps={{ inputProps: { min: 1 } }}
the min value should be passed to the component and the default should be 0

2022-03-09 15:19 UTC, maria-clipp commented on src/components/QuantityInput/QuantityInput.tsx
> +  const handleQuantifyValueChange = event => {
the second argument should be valued and can be used directly `event, value =>`, but this is just an observation rather than something that necessarily needs to be changed

2022-03-09 15:19 UTC, maria-clipp commented on src/components/QuantityInput/QuantityInput.tsx
> +    handleQuantifyChange(quantity + QUANTITY_STEP);
The step should be something optional that is passed to the components and should have a default value 1

2022-03-30 07:28 UTC, maria-clipp commented on src/components/PDP/PDP.tsx
> +    return isSignin ? 'Add to Cart' : 'Add to Quote';
We are not having a cart at this moment so this is not needed

2022-03-30 07:43 UTC, maria-clipp requested changes

2022-03-30 07:43 UTC, maria-clipp commented on src/components/PDP/PDP.tsx
> +  const renderStockQuantityText = useCallback(() => {
this should be extracted in a separate component

2022-03-30 07:43 UTC, maria-clipp commented on src/components/PDP/PDP.tsx
> +        pdpOptionGroups={pdpOptionGroups}
can we rename `pdpOptionGroups` to `productVariations`

2022-03-30 07:43 UTC, maria-clipp commented on src/components/PDP/PDP.tsx
> +            {isSignin && discountHint && <Typography variant="caption">{discountHint}</Typography>}
since we are already checking if the user is signed in before. rendering this section this check is unnecesary

2022-03-30 07:43 UTC, maria-clipp commented on src/components/PDP/PDP.tsx
> +        <>
Can we extract 2 components for logged and non logged in

2022-03-30 07:43 UTC, maria-clipp commented on src/components/PDPOptionsSelector/styles/PDPOptionsSelectorStyles.tsx
> +  '.MuiTextField-root': {
can we use `[`.${textFieldClasses.root}`]`
this is valid for line 27 as well

2022-03-30 07:43 UTC, maria-clipp commented on src/components/PDPOptionsSelector/styles/PDPOptionsSelectorStyles.tsx
> +  height: '70px !important',
why do we need important

2022-03-30 07:43 UTC, maria-clipp commented on src/components/QuantityInput/styles/QuantityInputStyles.tsx
> +  '& input': {
please use the class of the input rather the input element itself

2022-03-31 14:21 UTC, AngelGenchev95 approved these changes

2022-03-31 14:21 UTC, merged